<a href="https://colab.research.google.com/github/souravlouha/ML_Practice_Studio/blob/main/ANN_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive   # Import the Colab Drive module
drive.mount('/content/drive')    # Mount your Google Drive to access files in Colab


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
import pandas as pd  # Import the pandas library and give it the alias 'pd'
df = pd.read_csv('/content/drive/MyDrive/All_DataSets/Social_Network_Ads.csv')  # Read the CSV file from your Google Drive into a DataFrame called 'df'
df.head(5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
x= df.iloc[:,1:4].values# Extracts columns 1 to 3 (2nd to 4th columns) as a NumPy array from the DataFrame 'df'
x

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder  # Import LabelEncoder from sklearn
le = LabelEncoder()  # Create an instance of LabelEncoder

# Apply Label Encoding to the first column (column index 0) of the feature matrix 'x'
x[:, 0] = le.fit_transform(x[:, 0])

x  # Display the transformed array


array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [9]:
from sklearn.preprocessing import StandardScaler  # Import StandardScaler from sklearn

sc = StandardScaler()  # Create an instance of StandardScaler

# Fit the scaler to 'x' and transform it (i.e., scale all features)
x = sc.fit_transform(x)

x  # Display the standardized values


array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]])

In [10]:
# Extract the 5th column (index 4) from the DataFrame and store it in variable 'y'
y = df.iloc[:, 4].values

y  # Display the target/output values


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [11]:
from sklearn.model_selection import train_test_split# Split the dataset into training and testing sets (80% train, 20% test)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
# feature matrix
# target/output labels
# 20% of the data will be used for testing
# ensures reproducible results

In [12]:
# Checking the shape of the training feature set (rows, columns)
x_train.shape


(320, 3)

In [13]:
# Importing required libraries from Keras
from keras.models import Sequential
from keras.layers import Dense

# Initializing the Artificial Neural Network (ANN) model as a sequence of layers
ann_model = Sequential()

# Adding the input layer with 128 neurons and ReLU activation function
# input_shape=(3,) means the model expects 3 input features
ann_model.add(Dense(128, activation='relu', input_shape=(3,)))  # Input Layer

# Adding the first hidden layer with 64 neurons and ReLU activation
ann_model.add(Dense(64, activation='relu'))  # 1st Hidden Layer

# Adding the second hidden layer with 32 neurons and ReLU activation
ann_model.add(Dense(32, activation='relu'))  # 2nd Hidden Layer

# Adding the third hidden layer with 16 neurons and ReLU activation
ann_model.add(Dense(16, activation='relu'))  # 3rd Hidden Layer

# Adding the output layer with 1 neuron and sigmoid activation
# sigmoid is used for binary classification problems
ann_model.add(Dense(1, activation='sigmoid'))  # Output Layer

# Compiling the ANN model
# Optimizer: Adam (used for adjusting weights)
# Loss: Binary Crossentropy (used for binary classification)
# Metrics: Accuracy (used to evaluate the model performance)
ann_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Printing the summary of the ANN model structure
ann_model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,393 (44.50 KB)

 Trainable params: 11,393 (44.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Training the ANN model using the training data
history=ann_model.fit(x_train,y_train,epochs=100,batch_size=10,validation_data=(x_test,y_test))
# Input features for training
# Target labels for training
# Number of times the model will see the entire training dataset
# Number of samples per gradient update (i.e., the model updates weights after every 10 samples)
# Validation data used to evaluate model performance after each epoch


# The 'history' object stores training & validation loss and accuracy for each epoch

Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7216 - loss: 0.6487 - val_accuracy: 0.8875 - val_loss: 0.4178
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8351 - loss: 0.4224 - val_accuracy: 0.9000 - val_loss: 0.2045
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8812 - loss: 0.2959 - val_accuracy: 0.9250 - val_loss: 0.1717
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9069 - loss: 0.2361 - val_accuracy: 0.9500 - val_loss: 0.1733
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8783 - loss: 0.2769 - val_accuracy: 0.9500 - val_loss: 0.1621
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9105 - loss: 0.2456 - val_accuracy: 0.9500 - val_loss: 0.1580
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9343 - loss: 0.2052 - val_accuracy: 0.9500 - val_loss: 0.1637
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9227 - loss: 0.2432 - val_accuracy: 0.9500 - v

In [15]:
# Use the LabelEncoder (already fitted earlier) to transform the category 'Male' into a numerical label
# This is necessary because machine learning models work with numbers, not text/categorical values
k = le.transform(['Male'])[0]  # The transform method returns an array; [0] extracts the single value

# 'k' now stores the numeric code that corresponds to the category 'Male' (e.g., 1 if 'Male' was encoded as 1)
k  # Display or use the numeric value assigned to 'Male'


np.int64(1)

In [21]:
# Use the StandardScaler (sc) to scale the input features [k, 34, 56000]
# k: encoded gender (e.g., 0 or 1)
# 34: age
# 56000: salary
# The scaler was already fitted earlier on training data, so now we transform this new input to match the same scale
d_scale = sc.transform([[k, 34, 56000]])

# Display the scaled version of the input features
d_scale


array([[ 1.02020406, -0.34910049, -0.40354654]])

In [22]:
(ann_model.predict(d_scale)>0.5).astype('int32')
# Use the trained ANN model to predict the output for the scaled input data
# ann_model.predict(d_scale) returns a probability (between 0 and 1)
#   ann_model.predict(d_scale)

# Check if the predicted probability is greater than 0.5
# If yes, classify it as class 1; otherwise, class 0 (binary classification thresholding)
#   > 0.5

# Convert the boolean result (True/False) into integer (1/0)
# .astype('int32') ensures the final output is in integer format suitable for classification labels
#  .astype('int32')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[0]], dtype=int32)

In [23]:
y_test
# y_test is the actual/true labels (target values) of the test dataset — used to evaluate how well your trained model is performing.

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [24]:
y_pred=(ann_model.predict(x_test).ravel()>.5).astype('int32')
y_pred

## Use the trained ANN model to predict probabilities on the test dataset
# The output is a 2D array of probabilities (between 0 and 1) for each sample
#  y_pred = (ann_model.predict(x_test)

         # Flatten the 2D output array to 1D (from shape [n_samples, 1] to [n_samples])
        # .ravel()

         # Apply threshold: classify as 1 if probability > 0.5, else 0
        # > 0.5

         # Convert boolean values (True/False) to integer labels (1/0)
        # ).astype('int32')

# Display the predicted class labels for the test data
#  y_pred


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int32)

In [25]:
# Import necessary evaluation metrics: confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score

# Compute the confusion matrix using actual and predicted labels
# It shows TP, TN, FP, FN (True/False Positives/Negatives)
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
cm


array([[55,  3],
       [ 1, 21]])